export type Rect = { x: number; y: number; width: number; height: number };
export type MarkerGeometry = {
  framePath: string;
  visible: boolean;
  rect: Rect;
};
export type SelectorMatch = MarkerGeometry & { selector: string };
export type ObservedIframe = MarkerGeometry & { url: string };
export type ObservedScript = { framePath: string; url: string };
export type ObservedElement = {
  ref: string;
  framePath: string;
  origin?: string;
  fingerprint: string;
  role: string;
  name: string;
  iconHint?: string;
  identityName?: string;
  nameSource?: "spec" | "nearby";
  tag: string;
  inputType?: string;
  href?: string;
  rel?: string;
  ariaLabel?: string;
  paginationContainer?: boolean;
  pagination?: boolean;
  value?: string;
  placeholder?: string;
  checked: boolean;
  selected: boolean;
  disabled: boolean;
  readonly: boolean;
  required: boolean;
  invalid: boolean;
  rect: Rect;
  clickRect?: Rect;
  inViewport: boolean;
  distanceBelowFold: number;
  formId?: string;
  options?: string[];
  optionCount?: number;
  optionLabel?: string;
  landmark?: "header" | "nav";
  containerText?: string;
  itemPosition?: number;
  itemCount?: number;
  priority?: number;
};
export type ObservedForm = {
  id: string;
  active: boolean;
  fields: { ref: string; required: boolean; empty: boolean }[];
};
export type Observation = {
  url: string;
  title: string;
  readyState: DocumentReadyState;
  epoch: number;
  viewport: { width: number; height: number };
  scroll: { x: number; y: number; maxY: number };
  elements: ObservedElement[];
  text: string;
  headings: { level: number; text: string }[];
  forms: ObservedForm[];
  signals: {
    passwordFieldVisible: boolean;
    loginModalCoversViewport?: boolean;
    loginTextModal?: boolean;
    loginTextPanel?: boolean;
    mainLoginFormOnly?: boolean;
    modalOverlay: boolean;
    dialogOpen: boolean;
    iframeOrigins: string[];
    scriptOrigins: string[];
    markers?: {
      selectorMatches: SelectorMatch[];
      iframes: ObservedIframe[];
      scripts: ObservedScript[];
      scanMs: number;
    };
  };
  pageHash: string;
  timings: {
    snapshotMs: number;
    settleMs?: number;
    totalMs: number;
    framesSkipped?: number;
    framesFailed?: number;
    framesMs?: number;
    childFramesMs?: number;
  };
};
export type SnapshotOptions = {
  maxTextChars: number;
  textScanChars?: number;
  belowFoldScreens?: number;
  traverseFrames?: boolean;
  markerSelectors?: string[];
};
export type ObserveOptions = {
  settleNavigation?: boolean;
  goal?: string;
  maxElements?: number;
  belowFoldScreens?: number;
  maxTextChars?: number;
  markerSelectors?: string[];
  frameTimeoutMs?: number;
};
export type RefResolution = {
  status: "ok" | "stale-epoch" | "missing" | "identity-changed";
  drift?: boolean;
  rect?: Rect;
  clickPoint?: { x: number; y: number };
  visible?: boolean;
  enabled?: boolean;
  coveredBy?: { role: string; name: string };
  focusPath?: boolean;
  waitMs?: number;
  unmet?: "invisible" | "disabled" | "not-editable" | "covered" | "unstable";
  value?: string;
  valueLength?: number;
  valueChanged?: boolean;
  checked?: boolean;
  selectedIndex?: number;
  selectedLabel?: string;
  optionLabels?: string[];
  optionDisabled?: boolean[];
  selectPopup?: boolean;
};
